### PR TITLE
Add mandatory test, fix #41

### LINKED ISSUE #41: Wrong caches for Termux
File `.cache` in Termux saves `privileges` requirements, but Termux is not rooted by default. I will investigate Termux behaviour (I'm still learning how to use it), but for now it doesn't require `privileges` in caches, and as a matter of fact it will abort the script as soon as it starts.

### PR DESCRIPTION
**Pull request by archetipico**
Fixed paths and added mandatory testing when setting up.
Fixed #41.

### CODE REVIEW

**Review by MasterCruelty — COMMENTED** [review]
Ok, I've seen all the changes. I'll test It later

**Comment by archetipico** [comment]
I also fixed #41

**Comment by MasterCruelty** [comment]
> I also fixed #41 

I'll check this too asap

**Review by MasterCruelty — APPROVED** [review]
Ok

**Pull request merged**
